---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 35314.
--- DateTime: 2026/2/1 10:41
---

-- 参数列表
-- 优惠券ID
local voucherId = ARGV[1]
-- 用户ID
local userId = ARGV[2]
-- 订单ID
local orderId = ARGV[3]

local stockKey = 'seckill:stock:'..voucherId
local orderKey = 'seckill:order'.. voucherId

-- 业务
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足
    return 1
end

if (redis.call('sismember', orderKey, userId) == 1) then
    -- 重复下单
    return 2
end
-- 减库存
redis.call('incrby', stockKey, -1)
-- 下单
redis.call('sadd', orderKey, userId)
-- 发送订单信息到消息队列中 xadd stream.orders * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0